### ISSUE TITLE
fails with ansible 1.9.2

### ISSUE THREAD

**Issue by drzraf** [sbitio/ansible-munin#8]
> TASK: [sbitmedia.fail2ban | Configure fail2ban service in Munin] ************** 
> fatal: [myhost] => module is missing interpreter line - munin_plugin

Where
```module_path = ~/ansible/roles/sbitmedia.munin/library/munin_plugin```

Side question: are your Ansible modules still supported or not?
(this is important to know)

**Comment by drzraf** [comment]
Adding that:
> #!/usr/bin/python
> # -*- coding: utf-8 -*-

helped a little bit, but then failed on sbitmedia.fail2ban integration with sbitmedia.munin, I think these modules both need a small lifting.

**Comment by drzraf** [comment]
Worked around by adding the missing action_plugins lines to ansible.cfg

**Comment by jonhattan** [comment]
So there's something to do here? Or it was just a misconfiguration on your side?

About support status of this and [the other modules we've published](https://galaxy.ansible.com/list#/users/2581): we're not using them actively, since our client is no longer interested in ansible. But we try to accept PRs and keep an eye on issues, as time permits. OTOH we as a company use ansible internally for other things though.

**Comment by jonhattan** [comment]
Anyway added the shebang.

**Comment by drzraf** [comment]
Thank you for the status update.
